In [2]:
import torch
T1 = torch.tensor([1,2,5,4]).unsqueeze_(0)
T2 = torch.tensor([1,2,3,4]).unsqueeze_(0)
T3 = torch.tensor([2,2,3,4]).unsqueeze_(0)
a = []
a.append(T1)
a.append(T2)
a.append(T3)

c = torch.cat(a,dim=0)
print(c)

tensor([[1, 2, 5, 4],
        [1, 2, 3, 4],
        [2, 2, 3, 4]])


In [2]:
import numpy as np
a=[8]*2

print(a)

[8, 8]


In [3]:
import numpy as np
dat = np.array([i for i in range(-5, 6)])
print(dat)
dat = np.clip(dat, -3, 2)
print(dat)

[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[-3 -3 -3 -2 -1  0  1  2  2  2  2]


In [4]:
import torchvision.models as models
resnet152 = models.resnet152(pretrained=True)
print(resnet152)

/home/liuchang/anaconda3/envs/vlm/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/home/liuchang/anaconda3/envs/vlm/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=ResNet152_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet152_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [10]:
from torch.nn import functional as F
action = torch.Tensor(5, 8)
print(action.shape)
shape = [0, 0] * action.dim()
print(shape)
pad_len = 3
shape[-1] = pad_len
print(shape)
action = F.pad(action, tuple(shape), value=0)
print(action)
print(action.shape)

torch.Size([5, 8])
[0, 0, 0, 0]
[0, 0, 0, 3]
tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 4.4182e-33, 0.0000e+00,
         7.9411e-37, 0.0000e+00],
        [4.8149e+07, 4.5862e-41, 1.4013e-45, 0.0000e+00, 4.4842e-44, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.4842e-44, 0.0000e+00, 9.1845e-41, 1.1551e-40,
         1.1481e-41, 2.0739e-43],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00]])
torch.Size([8, 8])


In [28]:
a = torch.Tensor(3,128,128)
b = torch.Tensor(3,128,128)
c = torch.Tensor(3,128,128)
d = torch.Tensor([])
rgb = torch.cat([a.unsqueeze(0), b.unsqueeze(0), c.unsqueeze(0)])
pcd = torch.cat([d, rgb.unsqueeze(0)])
print(rgb.shape)
print(pcd.shape)


torch.Size([3, 3, 128, 128])
torch.Size([1, 3, 3, 128, 128])


In [48]:
a = torch.Tensor(65,3)
b = torch.Tensor(65,3)
x_acc = ((a[:,0] - b[:,0]) ** 2 ).mean().sqrt()
print(x_acc)
test = torch.Tensor((1,2,3))
s = test.sum().mean()
print(s)

tensor(187.1265)
tensor(6.)


In [8]:
import torch
device = torch.device("cuda",6)
print(device)

cuda:6


In [11]:
import torch
import numpy
a = torch.Tensor(100,2,4)
print(a.shape[0])
b = a.tolist()
print(len(b))
print(b[99])

100
100
[[1.974831291155871e+37, 4.5606659819915496e-41, 1.9748353476377918e+37, 4.5606659819915496e-41], [1.9748394041197126e+37, 4.5606659819915496e-41, 1.9748434606016333e+37, 4.5606659819915496e-41]]


In [4]:
import numpy as np
import torch
a = np.random.randint(0,256,size=(1,128,128))
print(a)
b = torch.tensor(a).float()

rgb = b / 255.0
rgb = 2 * (rgb - 0.5)
print(rgb)

[[[ 31  37 121 ... 159  19 208]
  [  8 175  77 ... 234 131  83]
  [140 249 151 ... 238  29  29]
  ...
  [134 214   4 ...  34   8 140]
  [ 19  60 200 ... 164   8 126]
  [238 189 213 ... 177 198 244]]]
tensor([[[-0.7569, -0.7098, -0.0510,  ...,  0.2471, -0.8510,  0.6314],
         [-0.9373,  0.3725, -0.3961,  ...,  0.8353,  0.0275, -0.3490],
         [ 0.0980,  0.9529,  0.1843,  ...,  0.8667, -0.7725, -0.7725],
         ...,
         [ 0.0510,  0.6784, -0.9686,  ..., -0.7333, -0.9373,  0.0980],
         [-0.8510, -0.5294,  0.5686,  ...,  0.2863, -0.9373, -0.0118],
         [ 0.8667,  0.4824,  0.6706,  ...,  0.3882,  0.5529,  0.9137]]])


In [8]:
from pathlib import Path
import os
taskvar_dir = Path("/home/liuchang/projects/VLMbench/VLMbench/hiverformer/packaged/pick_cube_size")
datanames = os.listdir(taskvar_dir)
print(datanames)

['variation0', 'variation2', 'variation1', 'variation3']


In [7]:
from amsolver.utils import get_stored_demos
from amsolver.observation_config import ObservationConfig
from pathlib import Path
select_frames = [0, 2, 56, 124, 167]
dataset_path = Path("/home/liuchang/DATA/rlbench_data/train")
img_size = [128, 128]
obs_config = ObservationConfig()
obs_config.set_all(True)
obs_config.right_shoulder_camera.image_size = img_size
obs_config.left_shoulder_camera.image_size = img_size
obs_config.overhead_camera.image_size = img_size
obs_config.wrist_camera.image_size = img_size
obs_config.front_camera.image_size = img_size

demos = get_stored_demos(1, False, dataset_path, 0, "pick_cube_color", obs_config , "episode0",selected_frame=select_frames)