In [3]:
import torch
T1 = torch.tensor([1,2,5,4]).unsqueeze_(0)
T2 = torch.tensor([1,2,3,4]).unsqueeze_(0)
T3 = torch.tensor([2,2,3,4]).unsqueeze_(0)
a = []
a.append(T1)
a.append(T2)
a.append(T3)

c = torch.cat(a,dim=0)
print(c)

tensor([[1, 2, 5, 4],
        [1, 2, 3, 4],
        [2, 2, 3, 4]])


In [2]:
import numpy as np
a=[8]*2

print(a)

[8, 8]


In [3]:
import numpy as np
dat = np.array([i for i in range(-5, 6)])
print(dat)
dat = np.clip(dat, -3, 2)
print(dat)

[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[-3 -3 -3 -2 -1  0  1  2  2  2  2]


In [9]:
import torch
a=torch.ones(2,5,2)
print(a)
print(a[:,1,:].shape)
print(a[:,:1,:].shape)



tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])
torch.Size([2, 2])
torch.Size([2, 1, 2])


In [9]:
a: tuple = ("wrist", "left_shoulder", "right_shoulder")
print(a[1])

left_shoulder
